### ISSUE TITLE
Request for dataset

### ISSUE THREAD

**Issue by USTfgaoaa** [donghaozhang/Anisotropic-Fast-Marching#4]

**Comment by USTfgaoaa** [comment]
Hi, 
I want to try your code. Could you please provide the dataset for testing? In trace_v2.m, 'xxx.mat' are loaded but not included in this repo. Many thanks.

**Comment by donghaozhang** [comment]
You can use any 3D tif for the input. The code is too dirty now. When I have time, I will do some maintenance. When I finish the maintenance, I will let you know.

**Comment by donghaozhang** [comment]
If you only interested in anisotropic fast marching, you can use defaultexampleafm.m in afmlib/afmmain folder. This one do not require any input.

**Comment by USTfgaoaa** [comment]
Ok, thanks a lot !
